### ISSUE TITLE
creating new release version for "Apple Devices" Support

### ISSUE THREAD

**Issue by MarcoPNS** [joz-k/ios_backup_extractor#2]
Hi! First of all, great job. Backup iOS Files so that you can access them is just a pain but your tool makes live easier. Regarding support for the "Apple Devices" App, I saw that you already implemented a fix. Would you like to create a new prebuild release?

Thank you.

**Comment by joz-k** [comment]
Hi. The new version 1.2.1 with "Apple Devices" app support has been just released.

**Comment by joz-k** [comment]
Hi. The new version 1.2.1 with "Apple Devices" app support has been just released.
